name             'cs312-hw-cookbook'
maintainer       'OSU Open Source Lab'
maintainer_email 'chef@osuosl.org'
license          'All rights reserved'
description      'Installs/Configures cs312-hw-cookbook'
long_description 'Installs/Configures cs312-hw-cookbook'
version          '0.0.1'
