name             'cs312-hw-cookbook'
maintainer       'OSU Open Source Lab'
maintainer_email 'chef@osuosl.org'
license          'Apache v2'
description      'Installs/Configures cs312-hw-cookbook'
long_description 'Installs/Configures cs312-hw-cookbook'
version          '0.0.1'

depends 'apache2'
depends 'iptables-ng'
